name: e_commerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.1
  cached_network_image: ^3.1.0+1
  card_swiper: ^1.0.4
  carousel_pro_nullsafety: ^1.0.2
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  easy_localization: ^3.0.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.8
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  json_annotation: ^4.3.0
  list_tile_switch: ^1.0.0
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.15
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/category/
    - assets/images/brand/
    - assets/translations/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android_gravity: center
